INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Login v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Login v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Login v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Login v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Login v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'hub v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'hub v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'hub v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'hub v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'hub v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Hospital Search v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Hospital Search v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Hospital Search v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Hospital Search v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Hospital Search v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Triage v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Triage v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Triage v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Triage v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Triage v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Config v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Config v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Config v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Config v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Config v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Doctor Workbench v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Doctor Workbench v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Doctor Workbench v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Doctor Workbench v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Doctor Workbench v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Backend System Localization v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 40, 'Backend System Localization v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Backend System Localization v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Backend System Localization v1.2', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 40, 'Backend System Localization v1.2', 'Back-end Developer');