INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (17, '刘国平', 'Liu Guoping', 'Back-end Developer', 'Login', 'Login');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (18, '刘硕', 'Liu Shuo', 'Back-end Developer', 'Login', 'Login');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (19, '闫光', 'Yan Guang', 'Back-end Developer', 'Login', 'Login');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (20, '张文辉', 'Zhang Wenhui', 'Back-end Developer', 'Login', 'Login');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (21, '陈西丹', 'Chen XiDan', 'Back-end Developer', 'hub', 'hub');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (22, '毛毅炯', 'Mao Yijiong', 'Back-end Developer', 'hub', 'hub');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (23, '潘宁', 'Pan Ning', 'Back-end Developer', 'hub', 'hub');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (24, '顾同同', 'Gu Tongtong', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (25, '钱雪艳', 'Qian Xueyan', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (26, '张建华', 'Zhang Jianhua', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (27, '谢晟立', 'Xie Shengli', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (28, '张华', 'Zhang Hua', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (29, '王仕成', 'Wang ShiCheng', 'Back-end Developer', 'Hospital Search', 'Hospital Search');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (30, '方亮', 'Fang Liang', 'Back-end Developer', 'Triage', 'Triage');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (31, '刘振业', 'Liu Zhenye', 'Back-end Developer', 'Triage', 'Triage');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (32, '彭宜堃', 'Peng Yikun', 'Back-end Developer', 'Triage', 'Triage');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (33, '黄奉线', 'Huang Fengxian', 'Back-end Developer', 'Triage', 'Triage');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (34, '傅璎俊', 'Fu Yingjun', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (35, '谢晟立', 'Xie Shengli', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (36, '黄奉线', 'Huang Fengxian', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (37, '雷倩', 'Lei Qian', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (38, '彭宜堃', 'Peng Yikun', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (39, '沈健', 'Shen Jian', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (40, '王瑞', 'Wang Rui', 'Back-end Developer', 'Config', 'Config');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (41, '甘炜', 'Gan Wei', 'Back-end Developer', 'Doctor Workbench', 'Doctor Workbench');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (42, '刘刚', 'Liu Gang', 'Back-end Developer', 'Doctor Workbench', 'Doctor Workbench');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (43, '刘国平', 'Liu Guoping', 'Back-end Developer', 'Doctor Workbench', 'Doctor Workbench');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (44, '王海清', 'Wang Haiqing', 'Back-end Developer', 'Doctor Workbench', 'Doctor Workbench');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (45, '郑婉枫', 'Zheng Wanfeng', 'Back-end Developer', 'Doctor Workbench', 'Doctor Workbench');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (46, '刘振宇', 'Liu Zhenyu', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (47, '王海清', 'Wang Haiqing', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (48, '黄奉线', 'Huang Fengxian', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (49, '彭宜堃', 'Peng Yikun', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (50, '王昌宇', 'Wang Changyu', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (51, '闫光', 'Yan Guang', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (52, '张文辉', 'Zhang Wenhui', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');
INSERT INTO db1.staff (id, staff_name, staff_en, staff_pos, department, module) VALUES (53, '柯宏喜', 'Ke Hongxi', 'Back-end Developer', 'Backend System Localization', 'Backend System Localization');