INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Login', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Login', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Login', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Login', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Login', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'hub', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'hub', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'hub', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'hub', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'hub', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Hospital Search', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Hospital Search', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Hospital Search', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Hospital Search', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Hospital Search', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Triage', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Triage', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Triage', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Triage', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Triage', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Config', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Config', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Config', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Config', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Config', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Doctor Workbench', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Doctor Workbench', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Doctor Workbench', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Doctor Workbench', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Doctor Workbench', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Design', 10, 'Backend System Localization', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Coding', 50, 'Backend System Localization', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Integration', 5, 'Backend System Localization', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Unit Test', 5, 'Backend System Localization', 'Back-end Developer');
INSERT INTO db1.task ( task_name, weight, module, staff_pos) VALUES ( 'Bug Fix', 30, 'Backend System Localization', 'Back-end Developer');